version: '0.1'

networks:
  mysql:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306
    networks:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    networks:
      - mysql
    