version: '0.1'

networks:
  ecommerce:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    ports:
      - "9000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - ecommerce

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: test
      PMA_PASSWORD: test
    networks:
      - ecommerce
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: ecommerce
      MYSQL_PORT: 9000
    networks:
      - ecommerce
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - ecommerce
    volumes:
      - ./frontend:/app
    