version: '0.1'

networks:
  ecommerce:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    ports:
      - "9000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - ecommerce
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: test
      PMA_PASSWORD: test
    networks:
      - ecommerce
    depends_on:
      mysql:
        condition: service_healthy
  
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: ecommerce
      JWT_SECRET: secret
      JWT_EXPIRY: 24h # 24 hours
    networks:
      - ecommerce
    volumes:
      - ./backend:/app
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - ecommerce
    volumes:
      - ./frontend:/app
    